package model;

import java.math.BigDecimal;

public class Estudiantes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.id
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.nombre
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.n1
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    private BigDecimal n1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.n2
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    private BigDecimal n2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.n3
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    private BigDecimal n3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Estudiantes.n4
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    private BigDecimal n4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.id
     *
     * @return the value of Estudiantes.id
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.id
     *
     * @param id the value for Estudiantes.id
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.nombre
     *
     * @return the value of Estudiantes.nombre
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.nombre
     *
     * @param nombre the value for Estudiantes.nombre
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.n1
     *
     * @return the value of Estudiantes.n1
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public BigDecimal getN1() {
        return n1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.n1
     *
     * @param n1 the value for Estudiantes.n1
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public void setN1(BigDecimal n1) {
        this.n1 = n1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.n2
     *
     * @return the value of Estudiantes.n2
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public BigDecimal getN2() {
        return n2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.n2
     *
     * @param n2 the value for Estudiantes.n2
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public void setN2(BigDecimal n2) {
        this.n2 = n2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.n3
     *
     * @return the value of Estudiantes.n3
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public BigDecimal getN3() {
        return n3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.n3
     *
     * @param n3 the value for Estudiantes.n3
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public void setN3(BigDecimal n3) {
        this.n3 = n3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Estudiantes.n4
     *
     * @return the value of Estudiantes.n4
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public BigDecimal getN4() {
        return n4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Estudiantes.n4
     *
     * @param n4 the value for Estudiantes.n4
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    public void setN4(BigDecimal n4) {
        this.n4 = n4;
    }
}