package map;

import java.util.List;
import model.Estudiantes;
import model.EstudiantesExample;
import org.apache.ibatis.annotations.Param;

public interface EstudiantesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    int countByExample(EstudiantesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    int deleteByExample(EstudiantesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    int insert(Estudiantes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    int insertSelective(Estudiantes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    List<Estudiantes> selectByExample(EstudiantesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    Estudiantes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    int updateByExampleSelective(@Param("record") Estudiantes record, @Param("example") EstudiantesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    int updateByExample(@Param("record") Estudiantes record, @Param("example") EstudiantesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    int updateByPrimaryKeySelective(Estudiantes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Estudiantes
     *
     * @mbggenerated Tue Feb 17 11:14:34 COT 2015
     */
    int updateByPrimaryKey(Estudiantes record);
}